name: serendy
description: Serendy app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0-63.1.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_remix_icon:
    git:
      url: https://github.com/mzeealii/flutter-remix-icon.git

  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.18.6

  # UI
  go_router: ^8.2.0
  dynamic_color: ^1.6.5
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  image_picker: ^0.8.9

  # Firebase
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.1
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.3

  # Others
  equatable: ^2.0.5
  ulid: ^2.0.0
  logger: ^1.4.0
  get_it: ^7.6.0
  google_sign_in: ^6.1.4
  json_annotation: ^4.8.1
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/emotions/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
