name: serendy
description: Serendy app
publish_to: "none"
version: 0.1.1-alpha+3

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # BaaS
  supabase_flutter: ^1.10.22

  # State
  equatable: ^2.0.5
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1

  # UI
  go_router: ^12.0.0
  animations: ^2.0.8
  flutter_remix_icon:
    git:
      url: https://github.com/mzeealii/flutter-remix-icon.git
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4
  responsive_builder: ^0.7.0
  cached_network_image: ^3.3.0
  youtube_player_flutter: ^8.1.2

  # Others
  ulid: ^2.0.0
  crypto: ^3.0.3
  google_sign_in: ^6.1.5
  flutter_appauth: ^6.0.2
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  flutter_cache_manager: ^3.3.1
  webview_flutter: ^4.4.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  custom_lint: ^0.5.4
  riverpod_lint: ^2.1.0
  riverpod_generator: ^2.3.2
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/logos/
    - assets/icons/ranks/
    - assets/icons/emotions/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
