fragment MediaFields on Media {
  id
  type
  status
  title
  image
  genres
  isAdult
  startDate
  endDate
}

query GetMedia($mediaId: ID!) {
  GetMedia(mediaId: $mediaId) {
    ...MediaFields
  }
}

query GetMediaList($title: String) {
  GetMediaList(title: $title) {
    ...MediaFields
  }
}

mutation AddMedia(
  $type: MediaType!
  $status: MediaStatus!
  $title: String!
  $image: String!
  $genres: [String!]!
  $isAdult: Boolean
  $startDate: DateTime
  $endDate: DateTime
) {
  AddMedia(
    type: $type
    status: $status
    title: $title
    image: $image
    genres: $genres
    isAdult: $isAdult
    startDate: $startDate
    endDate: $endDate
  ) {
    ...MediaFields
  }
}
