fragment ThemeFields on Theme {
  owner {
    id
    name
  }
  items {
    id
    title
    image
    addedAt
  }
  id
  title
  image
  private
  total
}

query GetTheme($themeId: ID!) {
  GetTheme(themeId: $themeId) {
    ...ThemeFields
  }
}

query GetThemeList($ownerId: ID) {
  GetThemeList(ownerId: $ownerId) {
    ...ThemeFields
  }
}

mutation CreateTheme($title: String!) {
  CreateTheme(title: $title)
}
