fragment UserFields on User {
  id
  name
  email
  image
}

query GetMe {
  GetMe {
    ...UserFields
  }
}

mutation SignUp($name: String!, $email: String!, $image: String) {
  SignUp(name: $name, email: $email, image: $image) {
    id
  }
}

mutation EditUser($name: String, $email: String, $image: String) {
  EditUser(name: $name, email: $email, image: $image) {
    id
  }
}

mutation RemoveUser($reason: String) {
  RemoveUser(reason: $reason)
}
